### ISSUE TITLE
Introducción a PHP y MySQL

### ISSUE THREAD

**Issue by DanielLoredo** [DanielLoredo/RoboLinks-BackEnd#1]
**Objetivo**

- Aprender los aspectos básicos de Laravel, PHP y MySQL
- Desarrollar las funciones básicas de una API

**Videos:**

- https://www.youtube.com/watch?v=bPMcfSu9I6E&ab_channel=irpiricode
- https://www.youtube.com/watch?v=3Qt0Y7O3XM0&ab_channel=irpiricode
- https://www.youtube.com/watch?v=o_j00GB2s30&t=90s&ab_channel=irpiricode

**Deliverables:**

- [ ] Captura de pantalla de POSTMAN (Get y Post request)

**Comment by JorgeLoredo-1852** [comment]
<img width="958" alt="php2" src="https://user-images.githubusercontent.com/69738879/107296182-82319d80-6a36-11eb-81d9-7b5c7c0030f7.PNG">
<img width="958" alt="php1" src="https://user-images.githubusercontent.com/69738879/107296189-8362ca80-6a36-11eb-8245-8fbda721c52a.PNG">


En lugar de usar los datos de los empleados como en el ejemplo hice algunas variables sobre Links
