### ISSUE TITLE
[Feature] Auth and User request

### ISSUE THREAD

**Issue by DanielLoredo** [DanielLoredo/RoboLinks-BackEnd#10]
**Objetivo:**

- Investigar el uso e implementación de Google Auth 2.0 para el login
- Crear un archivo JSON para los usuarios segmentados en "user" y "admin", usa dummy text
- GET request para obtener la lista de usuarios como se planteó en la junta :)

**Notas:**

- Si puedes haz un script para probar Google Auth

**Comment by JorgeLoredo-1852** [comment]
Para usar la auth de Google existe un package llamado "react-google-login" con un componente que sólo ocupa el client ID de google cloud, esta sencillo en este video se explica mejor :
**https://www.youtube.com/watch?v=KmCI9Nlb_9I&ab_channel=TechWorth**

Creo que si es gratis hasta 100 usuarios y después de esos usuarios de prueba es probable que no te cobren pero te pidan autenticar tu APP, tons creo que si la podemos usar :D

**Nota:**
Otro acercamiento más largo sería utilizar "window.gapi.load("client:auth2", function)", y aunque es más riguroso, creo que permite una mejor recuperación del email del usuario y un login/logout más moldeable
