### ISSUE TITLE
[Feature] POST and DELETE request

### ISSUE THREAD

**Issue by DanielLoredo** [DanielLoredo/RoboLinks-BackEnd#14]
**Task**
- Create the POST and DELETE request for the Link model
- Remember to use special fields wherever it applies (unique, required, enum)

**Optional**
- Create the PATCH request 
- Create GET by id method to return only one Link

**Comment by teapot2** [comment]
Esto ya está si lo quieres revisar, fue el commit que hice a main por accidente
