### ISSUE TITLE
Introducción a PHP y MySQL

### ISSUE THREAD

**Issue by DanielLoredo** [DanielLoredo/RoboLinks-BackEnd#2]
**Objetivo**

- Aprender los aspectos básicos de Laravel, PHP y MySQL
- Desarrollar las funciones básicas de una API

**Videos:**

- https://www.youtube.com/watch?v=bPMcfSu9I6E&ab_channel=irpiricode
- https://www.youtube.com/watch?v=3Qt0Y7O3XM0&ab_channel=irpiricode
- https://www.youtube.com/watch?v=o_j00GB2s30&t=90s&ab_channel=irpiricode

**Deliverables:**

- [x] Captura de pantalla de POSTMAN (Get y Post request)

**Comment by teapot2** [comment]
![image](https://user-images.githubusercontent.com/33473370/107587975-69f18800-6bc8-11eb-9688-e1d406d42562.png)

![image](https://user-images.githubusercontent.com/33473370/107587995-737af000-6bc8-11eb-9fe3-be88bd4eb61f.png)
